<script setup>
import { Head } from '@inertiajs/vue3';

const props = defineProps({
    leads: Array,
    filters: Object,
    printTime: String,
});
</script>

<template>
    <Head title="Lead Report - Print" />
    
    <div class="printable-container">
        <!-- External Bootstrap for Printing -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        
        <div class="btn-group no-print">
            <button onclick="window.print()" class="btn btn-primary">Print Now</button>
            <button onclick="window.close()" class="btn btn-secondary ml-2">Close Window</button>
        </div>

        <div style="width: 95%; margin: auto;">
            <div class="row m-t-30 m-b-30">
                <div class="col-12 text-center company-name pb-3">
                    <h2 class="font-weight-bold">CRM - LEAD REPORT</h2>
                    <p class="m-0">Generating strategic insights and data summaries</p>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-6">
                    <p style="font-size: 14px" class="m-0"><strong>Printing Date & Time:</strong> {{ printTime }}</p>
                </div>
                <div class="col-6 text-right">
                    <p style="font-size: 14px" class="m-0"><strong>Total Records:</strong> {{ leads.length }}</p>
                </div>
            </div>

            <table class="table table-bordered table-striped">
                <thead class="thead-light text-center">
                    <tr>
                        <th>#</th>
                        <th>Created Date</th>
                        <th>Lead Name</th>
                        <th>Phone</th>
                        <th>Project/Service</th>
                        <th>Status</th>
                        <th>Assigned User</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    <tr v-for="(lead, index) in leads" :key="lead.id">
                        <td>{{ index + 1 }}</td>
                        <td>{{ new Date(lead.created_at).toLocaleDateString() }}</td>
                        <td class="text-left font-weight-bold">{{ lead.name }}</td>
                        <td>{{ lead.phone }}</td>
                        <td>{{ lead.service?.name || '-' }}</td>
                        <td>
                            <span class="badge" 
                                :class="{
                                    'badge-success': lead.status?.name.toLowerCase().includes('won'),
                                    'badge-danger': lead.status?.name.toLowerCase().includes('lost'),
                                    'badge-info': !lead.status?.name.toLowerCase().includes('won') && !lead.status?.name.toLowerCase().includes('lost')
                                }">
                                {{ lead.status?.name }}
                            </span>
                        </td>
                        <td>{{ lead.assigned_user?.name || 'Unassigned' }}</td>
                    </tr>
                    <tr v-if="leads.length === 0">
                        <td colspan="7" class="py-5">No leads metadata found for the selected period.</td>
                    </tr>
                </tbody>
            </table>

            <div class="row mt-5">
                <div class="col-4 border-top text-center pt-2">
                    <p class="small">Generated By CRM</p>
                </div>
                <div class="col-4"></div>
                <div class="col-4 border-top text-center pt-2">
                    <p class="small">Authorized Signature</p>
                </div>
            </div>
        </div>
    </div>
</template>

<style>
/* Global styles for this printable component only */
@media screen {
    body { background-color: #f4f4f4; padding: 20px 0; }
    .printable-container { background-color: white; padding-bottom: 50px; }
}

@media print {
    body { background-color: white; padding: 0; }
    .no-print { display: none !important; }
    .table-bordered th, .table-bordered td { border: 1px solid rgba(0,0,0,.3) !important; }
}

.table td { vertical-align: middle; }
.m-b-30{ margin-bottom: 30px; }
.m-t-30{ margin-top: 30px; }
.company-name{ border-bottom: 1px solid rgba(0,0,0,.3); }
.btn-group { width: 95%; margin: 20px auto; text-align: right; }
</style>
